// Mock Students
export const students = [
  {
    id: "S001",
    admissionNumber: "MDA-2024-001",
    name: "Ahmed Bin Abdullah",
    gender: "male",
    dateOfBirth: "2014-03-12",
    address: "12, Mosque Road, Calicut",
    photo: null,
    class: "Class 4",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P001",
    fatherName: "Abdullah Rahman",
    motherName: "Fathima Bivi",
    phone: "9876543210",
  },
  {
    id: "S002",
    admissionNumber: "MDA-2024-002",
    name: "Ibrahim Khaleel",
    gender: "male",
    dateOfBirth: "2013-08-22",
    address: "45, Palm Street, Calicut",
    photo: null,
    class: "Class 4",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P002",
    fatherName: "Khaleel Ahmed",
    motherName: "Mariam Beevi",
    phone: "9876543211",
  },
  {
    id: "S003",
    admissionNumber: "MDA-2024-003",
    name: "Yusuf Salim",
    gender: "male",
    dateOfBirth: "2014-01-05",
    address: "78, Green Lane, Calicut",
    photo: null,
    class: "Class 4",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P003",
    fatherName: "Salim Mohammed",
    motherName: "Zainab Beevi",
    phone: "9876543212",
  },
  {
    id: "S004",
    admissionNumber: "MDA-2024-004",
    name: "Fatima Zahra",
    gender: "female",
    dateOfBirth: "2014-05-15",
    address: "33, Rose Garden, Calicut",
    photo: null,
    class: "Class 4",
    division: "B",
    joiningDate: "2024-06-01",
    parentId: "P004",
    fatherName: "Zakariya Hassan",
    motherName: "Khadija Beevi",
    phone: "9876543213",
  },
  {
    id: "S005",
    admissionNumber: "MDA-2024-005",
    name: "Aisha Siddiqui",
    gender: "female",
    dateOfBirth: "2013-11-30",
    address: "22, Crescent Avenue, Calicut",
    photo: null,
    class: "Class 4",
    division: "B",
    joiningDate: "2024-06-01",
    parentId: "P005",
    fatherName: "Siddique Ali",
    motherName: "Ruqaiya Beevi",
    phone: "9876543214",
  },
  {
    id: "S006",
    admissionNumber: "MDA-2024-006",
    name: "Umar Farooq",
    gender: "male",
    dateOfBirth: "2015-02-18",
    address: "56, Hilal Street, Calicut",
    photo: null,
    class: "Class 3",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P001",
    fatherName: "Abdullah Rahman",
    motherName: "Fathima Bivi",
    phone: "9876543210",
  },
  {
    id: "S007",
    admissionNumber: "MDA-2024-007",
    name: "Maryam Noor",
    gender: "female",
    dateOfBirth: "2015-07-09",
    address: "90, Jasmine Road, Calicut",
    photo: null,
    class: "Class 3",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P006",
    fatherName: "Noor Mohammed",
    motherName: "Hafsa Beevi",
    phone: "9876543215",
  },
  {
    id: "S008",
    admissionNumber: "MDA-2024-008",
    name: "Hamza Rashid",
    gender: "male",
    dateOfBirth: "2016-04-25",
    address: "14, Olive Street, Calicut",
    photo: null,
    class: "Class 2",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P007",
    fatherName: "Rashid Ahmed",
    motherName: "Sumaiya Beevi",
    phone: "9876543216",
  },
];

// Mock Teachers
export const teachers = [
  {
    id: "T001",
    name: "Usthad Abdul Kareem",
    phone: "9988776655",
    email: "kareem@madrasa.com",
    subject: "Quran & Islamic Studies",
    classes: ["Class 4", "Class 3"],
    joiningDate: "2020-06-01",
    qualification: "B.A Islamic Studies",
  },
  {
    id: "T002",
    name: "Usthada Zubeda",
    phone: "9988776644",
    email: "zubeda@madrasa.com",
    subject: "Arabic",
    classes: ["Class 4", "Class 2"],
    joiningDate: "2021-06-01",
    qualification: "M.A Arabic",
  },
  {
    id: "T003",
    name: "Usthad Rasheed",
    phone: "9988776633",
    email: "rasheed@madrasa.com",
    subject: "Fiqh & Hadith",
    classes: ["Class 3"],
    joiningDate: "2019-06-01",
    qualification: "Dars Graduation",
  },
];

// Mock Parents
export const parents = [
  {
    id: "P001",
    fatherName: "Abdullah Rahman",
    motherName: "Fathima Bivi",
    phone: "9876543210",
    email: "abdullah@email.com",
    password: "parent123",
    children: ["S001", "S006"],
  },
  {
    id: "P002",
    fatherName: "Khaleel Ahmed",
    motherName: "Mariam Beevi",
    phone: "9876543211",
    email: "khaleel@email.com",
    password: "parent123",
    children: ["S002"],
  },
  {
    id: "P003",
    fatherName: "Salim Mohammed",
    motherName: "Zainab Beevi",
    phone: "9876543212",
    email: "salim@email.com",
    password: "parent123",
    children: ["S003"],
  },
  {
    id: "P004",
    fatherName: "Zakariya Hassan",
    motherName: "Khadija Beevi",
    phone: "9876543213",
    email: "zakariya@email.com",
    password: "parent123",
    children: ["S004"],
  },
  {
    id: "P005",
    fatherName: "Siddique Ali",
    motherName: "Ruqaiya Beevi",
    phone: "9876543214",
    email: "siddique@email.com",
    password: "parent123",
    children: ["S005"],
  },
];

// Mock Attendance Records  (status: present | absent | late | excused)
export const attendanceRecords = [
  // ── Class 4 ──
  { date:"2026-03-17", classId:"Class 4", records:[
    { studentId:"S001", status:"present", remark:"" },
    { studentId:"S002", status:"present", remark:"" },
    { studentId:"S003", status:"absent",  remark:"Sick" },
    { studentId:"S004", status:"present", remark:"" },
    { studentId:"S005", status:"late",    remark:"Bus delay" },
  ]},
  { date:"2026-03-14", classId:"Class 4", records:[
    { studentId:"S001", status:"present", remark:"" },
    { studentId:"S002", status:"present", remark:"" },
    { studentId:"S003", status:"absent",  remark:"Sick" },
    { studentId:"S004", status:"present", remark:"" },
    { studentId:"S005", status:"present", remark:"" },
  ]},
  { date:"2026-03-13", classId:"Class 4", records:[
    { studentId:"S001", status:"present", remark:"" },
    { studentId:"S002", status:"absent",  remark:"Family event" },
    { studentId:"S003", status:"present", remark:"" },
    { studentId:"S004", status:"present", remark:"" },
    { studentId:"S005", status:"absent",  remark:"" },
  ]},
  { date:"2026-03-12", classId:"Class 4", records:[
    { studentId:"S001", status:"present", remark:"" },
    { studentId:"S002", status:"present", remark:"" },
    { studentId:"S003", status:"late",    remark:"Late arrival" },
    { studentId:"S004", status:"absent",  remark:"Medical" },
    { studentId:"S005", status:"present", remark:"" },
  ]},
  { date:"2026-03-11", classId:"Class 4", records:[
    { studentId:"S001", status:"present", remark:"" },
    { studentId:"S002", status:"present", remark:"" },
    { studentId:"S003", status:"excused", remark:"Doctor appointment" },
    { studentId:"S004", status:"present", remark:"" },
    { studentId:"S005", status:"present", remark:"" },
  ]},
  { date:"2026-03-10", classId:"Class 4", records:[
    { studentId:"S001", status:"present", remark:"" },
    { studentId:"S002", status:"late",    remark:"" },
    { studentId:"S003", status:"absent",  remark:"" },
    { studentId:"S004", status:"present", remark:"" },
    { studentId:"S005", status:"present", remark:"" },
  ]},
  { date:"2026-03-07", classId:"Class 4", records:[
    { studentId:"S001", status:"present", remark:"" },
    { studentId:"S002", status:"present", remark:"" },
    { studentId:"S003", status:"present", remark:"" },
    { studentId:"S004", status:"present", remark:"" },
    { studentId:"S005", status:"absent",  remark:"" },
  ]},
  { date:"2026-03-06", classId:"Class 4", records:[
    { studentId:"S001", status:"present", remark:"" },
    { studentId:"S002", status:"present", remark:"" },
    { studentId:"S003", status:"absent",  remark:"Sick" },
    { studentId:"S004", status:"late",    remark:"" },
    { studentId:"S005", status:"present", remark:"" },
  ]},
  // ── Class 3 ──
  { date:"2026-03-17", classId:"Class 3", records:[
    { studentId:"S006", status:"present", remark:"" },
    { studentId:"S007", status:"absent",  remark:"Sick" },
  ]},
  { date:"2026-03-14", classId:"Class 3", records:[
    { studentId:"S006", status:"present", remark:"" },
    { studentId:"S007", status:"present", remark:"" },
  ]},
  { date:"2026-03-13", classId:"Class 3", records:[
    { studentId:"S006", status:"late",    remark:"" },
    { studentId:"S007", status:"present", remark:"" },
  ]},
  // ── Class 2 ──
  { date:"2026-03-17", classId:"Class 2", records:[
    { studentId:"S008", status:"present", remark:"" },
  ]},
  { date:"2026-03-14", classId:"Class 2", records:[
    { studentId:"S008", status:"absent",  remark:"Sick" },
  ]},
];

export const attendanceSummary = [
  { month: "Oct", present: 22, absent: 2 },
  { month: "Nov", present: 20, absent: 4 },
  { month: "Dec", present: 18, absent: 6 },
  { month: "Jan", present: 23, absent: 1 },
  { month: "Feb", present: 21, absent: 3 },
  { month: "Mar", present: 12, absent: 3 },
];

// Mock Homework
export const homeworkList = [
  {
    id: "HW001",
    type: "daily",
    title: "Memorize Surah Al-Asr",
    description: "Memorize Surah Al-Asr with proper tajweed. Focus on makhraj of ع and ص.",
    assignedDate: "2026-03-14",
    dueDate: "2026-03-15",
    class: "Class 4",
    teacherId: "T001",
    subject: "Quran",
    priority: "high",
    studentStatuses: [
      { studentId: "S001", status: "green",  parentConfirmed: true,  teacherVerified: true,  feedback: "Excellent tajweed!", note: "" },
      { studentId: "S002", status: "yellow", parentConfirmed: true,  teacherVerified: false, feedback: "", note: "Almost there, check ص makhraj" },
      { studentId: "S003", status: "red",    parentConfirmed: false, teacherVerified: false, feedback: "", note: "" },
      { studentId: "S004", status: "green",  parentConfirmed: true,  teacherVerified: true,  feedback: "Perfect recitation", note: "" },
      { studentId: "S005", status: "yellow", parentConfirmed: true,  teacherVerified: false, feedback: "", note: "" },
    ],
  },
  {
    id: "HW002",
    type: "long",
    title: "Memorize Surah Al-Kahf (1-20)",
    description: "Memorize first 20 ayahs of Surah Al-Kahf with tarteel. Weekly check every Friday.",
    assignedDate: "2026-03-10",
    dueDate: "2026-03-20",
    class: "Class 4",
    teacherId: "T001",
    subject: "Quran",
    priority: "high",
    studentStatuses: [
      { studentId: "S001", status: "green",  parentConfirmed: true,  teacherVerified: true,  progress: 100, feedback: "Completed ahead of schedule!", note: "" },
      { studentId: "S002", status: "yellow", parentConfirmed: true,  teacherVerified: false, progress: 60,  feedback: "", note: "Keep consistent daily revision" },
      { studentId: "S003", status: "red",    parentConfirmed: false, teacherVerified: false, progress: 0,   feedback: "", note: "Needs immediate attention" },
      { studentId: "S004", status: "yellow", parentConfirmed: true,  teacherVerified: false, progress: 80,  feedback: "", note: "" },
      { studentId: "S005", status: "red",    parentConfirmed: false, teacherVerified: false, progress: 20,  feedback: "", note: "Struggling – recommend extra session" },
    ],
  },
  {
    id: "HW003",
    type: "daily",
    title: "Arabic Vocabulary Exercise",
    description: "Complete vocabulary exercises on page 45-46. Write 5 sentences using new words.",
    assignedDate: "2026-03-14",
    dueDate: "2026-03-15",
    class: "Class 4",
    teacherId: "T002",
    subject: "Arabic",
    priority: "medium",
    studentStatuses: [
      { studentId: "S001", status: "yellow",   parentConfirmed: true,  teacherVerified: false, feedback: "", note: "" },
      { studentId: "S002", status: "green",    parentConfirmed: true,  teacherVerified: true,  feedback: "Good work", note: "" },
      { studentId: "S003", status: "yellow",   parentConfirmed: true,  teacherVerified: false, feedback: "", note: "" },
      { studentId: "S004", status: "red",      parentConfirmed: false, teacherVerified: false, feedback: "", note: "" },
      { studentId: "S005", status: "returned", parentConfirmed: true,  teacherVerified: true,  feedback: "Re-submitted with corrections", note: "" },
    ],
  },
  {
    id: "HW004",
    type: "daily",
    title: "Fiqh – Rules of Wudu",
    description: "Write down the 6 fardh of wudu from memory and explain each step briefly.",
    assignedDate: "2026-03-13",
    dueDate: "2026-03-14",
    class: "Class 4",
    teacherId: "T001",
    subject: "Fiqh",
    priority: "medium",
    studentStatuses: [
      { studentId: "S001", status: "green",  parentConfirmed: true,  teacherVerified: true,  feedback: "All 6 correct!", note: "" },
      { studentId: "S002", status: "green",  parentConfirmed: true,  teacherVerified: true,  feedback: "Well done", note: "" },
      { studentId: "S003", status: "red",    parentConfirmed: false, teacherVerified: false, feedback: "", note: "3rd consecutive miss" },
      { studentId: "S004", status: "yellow", parentConfirmed: true,  teacherVerified: false, feedback: "", note: "" },
      { studentId: "S005", status: "green",  parentConfirmed: true,  teacherVerified: true,  feedback: "Good effort", note: "" },
    ],
  },
  {
    id: "HW005",
    type: "daily",
    title: "Islamic Studies – Pillars of Islam",
    description: "Write a short paragraph on each of the 5 pillars of Islam with evidence from Quran/Hadith.",
    assignedDate: "2026-03-12",
    dueDate: "2026-03-13",
    class: "Class 4",
    teacherId: "T001",
    subject: "Islamic Studies",
    priority: "low",
    studentStatuses: [
      { studentId: "S001", status: "green",    parentConfirmed: true,  teacherVerified: true,  feedback: "Outstanding research", note: "" },
      { studentId: "S002", status: "returned", parentConfirmed: true,  teacherVerified: true,  feedback: "Returned after correction", note: "" },
      { studentId: "S003", status: "red",      parentConfirmed: false, teacherVerified: false, feedback: "", note: "" },
      { studentId: "S004", status: "green",    parentConfirmed: true,  teacherVerified: true,  feedback: "Excellent references", note: "" },
      { studentId: "S005", status: "yellow",   parentConfirmed: true,  teacherVerified: false, feedback: "", note: "" },
    ],
  },
  {
    id: "HW006",
    type: "long",
    title: "Arabic Essay – My Madrasa",
    description: "Write a 10-line essay in Arabic about your madrasa experience. Due before Friday prayer.",
    assignedDate: "2026-03-10",
    dueDate: "2026-03-14",
    class: "Class 3",
    teacherId: "T002",
    subject: "Arabic",
    priority: "medium",
    studentStatuses: [
      { studentId: "S006", status: "green",  parentConfirmed: true,  teacherVerified: true,  progress: 100, feedback: "Beautifully written!", note: "" },
      { studentId: "S007", status: "yellow", parentConfirmed: true,  teacherVerified: false, progress: 70,  feedback: "", note: "" },
    ],
  },
  {
    id: "HW007",
    type: "daily",
    title: "Quran Revision – Juz Amma",
    description: "Recite the last 10 surahs of Juz Amma to a parent and get signature.",
    assignedDate: "2026-03-15",
    dueDate: "2026-03-16",
    class: "Class 3",
    teacherId: "T001",
    subject: "Quran",
    priority: "high",
    studentStatuses: [
      { studentId: "S006", status: "red",    parentConfirmed: false, teacherVerified: false, feedback: "", note: "" },
      { studentId: "S007", status: "yellow", parentConfirmed: true,  teacherVerified: false, feedback: "", note: "" },
    ],
  },
  {
    id: "HW008",
    type: "daily",
    title: "Fiqh – Rules of Salah",
    description: "List the conditions that invalidate salah and memorize the short dua after salah.",
    assignedDate: "2026-03-10",
    dueDate: "2026-03-11",
    class: "Class 2",
    teacherId: "T001",
    subject: "Fiqh",
    priority: "low",
    studentStatuses: [
      { studentId: "S008", status: "green", parentConfirmed: true, teacherVerified: true, feedback: "Good effort for first try!", note: "" },
    ],
  },
];

// Mock Diary Entries
export const diaryEntries = [
  {
    id: "D001",
    date: "2026-03-14",
    class: "Class 4",
    teacherId: "T001",
    type: "class",
    title: "Surah Rahman Revision",
    content: "Today students revised Surah Rahman verses 1-30. Overall recitation was good. Please revise again at home with proper tajweed focus on makhraj.",
    targetStudentId: null,
  },
  {
    id: "D002",
    date: "2026-03-14",
    class: "Class 4",
    teacherId: "T001",
    type: "student",
    title: "Special Note – Ahmed",
    content: "Ahmed showed excellent improvement in tajweed today. His makhraj for 'ain and ghayn are now correct. Encourage him to continue.",
    targetStudentId: "S001",
  },
  {
    id: "D003",
    date: "2026-03-13",
    class: "Class 4",
    teacherId: "T001",
    type: "class",
    title: "New Lesson Started",
    content: "Started new chapter on Surah Al-Kahf. Students were given first 5 ayahs for home memorization. Please ensure daily revision.",
    targetStudentId: null,
  },
];

// Mock Exam Records
export const exams = [
  // ─── Class 4 Exams ───────────────────────────────────────────────────────
  {
    id: "EX001",
    name: "First Semester Exam",
    type: "semester",
    date: "2026-01-20",
    class: "Class 4",
    subjects: ["Quran", "Arabic", "Fiqh", "Islamic Studies"],
    totalMarks: 100,
    status: "published",   // draft | marks_entered | published
    results: [
      { studentId: "S001", marks: { Quran: 92, Arabic: 88, Fiqh: 85, "Islamic Studies": 90 }, total: 355, grade: "A+", rank: 1 },
      { studentId: "S002", marks: { Quran: 78, Arabic: 82, Fiqh: 75, "Islamic Studies": 80 }, total: 315, grade: "B+", rank: 3 },
      { studentId: "S003", marks: { Quran: 65, Arabic: 70, Fiqh: 60, "Islamic Studies": 72 }, total: 267, grade: "C",  rank: 5 },
      { studentId: "S004", marks: { Quran: 88, Arabic: 90, Fiqh: 82, "Islamic Studies": 86 }, total: 346, grade: "A",  rank: 2 },
      { studentId: "S005", marks: { Quran: 80, Arabic: 76, Fiqh: 78, "Islamic Studies": 82 }, total: 316, grade: "B+", rank: 4 },
    ],
  },
  {
    id: "EX002",
    name: "Monthly Test – March",
    type: "class_test",
    date: "2026-03-10",
    class: "Class 4",
    subjects: ["Quran", "Arabic"],
    totalMarks: 50,
    status: "published",
    results: [
      { studentId: "S001", marks: { Quran: 47, Arabic: 46 }, total: 93,  grade: "A+", rank: 1 },
      { studentId: "S002", marks: { Quran: 38, Arabic: 40 }, total: 78,  grade: "B",  rank: 3 },
      { studentId: "S003", marks: { Quran: 30, Arabic: 32 }, total: 62,  grade: "C",  rank: 5 },
      { studentId: "S004", marks: { Quran: 44, Arabic: 45 }, total: 89,  grade: "A",  rank: 2 },
      { studentId: "S005", marks: { Quran: 40, Arabic: 38 }, total: 78,  grade: "B",  rank: 3 },
    ],
  },
  {
    id: "EX003",
    name: "Monthly Test – February",
    type: "class_test",
    date: "2026-02-10",
    class: "Class 4",
    subjects: ["Quran", "Arabic"],
    totalMarks: 50,
    status: "published",
    results: [
      { studentId: "S001", marks: { Quran: 45, Arabic: 44 }, total: 89,  grade: "A+", rank: 1 },
      { studentId: "S002", marks: { Quran: 36, Arabic: 38 }, total: 74,  grade: "B",  rank: 3 },
      { studentId: "S003", marks: { Quran: 28, Arabic: 30 }, total: 58,  grade: "C",  rank: 5 },
      { studentId: "S004", marks: { Quran: 42, Arabic: 43 }, total: 85,  grade: "A",  rank: 2 },
      { studentId: "S005", marks: { Quran: 38, Arabic: 36 }, total: 74,  grade: "B",  rank: 3 },
    ],
  },
  {
    id: "EX004",
    name: "Hifz Assessment – Q1",
    type: "hifz",
    date: "2026-03-05",
    class: "Class 4",
    subjects: ["Memorization", "Tajweed"],
    totalMarks: 100,
    status: "marks_entered",
    results: [
      { studentId: "S001", marks: { Memorization: 95, Tajweed: 90 }, total: 185, grade: "A+", rank: 1 },
      { studentId: "S002", marks: { Memorization: 80, Tajweed: 78 }, total: 158, grade: "B+", rank: 3 },
      { studentId: "S003", marks: { Memorization: 62, Tajweed: 60 }, total: 122, grade: "C",  rank: 5 },
      { studentId: "S004", marks: { Memorization: 92, Tajweed: 88 }, total: 180, grade: "A+", rank: 2 },
      { studentId: "S005", marks: { Memorization: 75, Tajweed: 72 }, total: 147, grade: "B",  rank: 4 },
    ],
  },
  // ─── Class 3 Exams ───────────────────────────────────────────────────────
  {
    id: "EX005",
    name: "First Semester Exam",
    type: "semester",
    date: "2026-01-22",
    class: "Class 3",
    subjects: ["Quran", "Arabic", "Fiqh", "Islamic Studies"],
    totalMarks: 100,
    status: "published",
    results: [
      { studentId: "S006", marks: { Quran: 85, Arabic: 80, Fiqh: 78, "Islamic Studies": 82 }, total: 325, grade: "A",  rank: 1 },
      { studentId: "S007", marks: { Quran: 72, Arabic: 68, Fiqh: 70, "Islamic Studies": 74 }, total: 284, grade: "B",  rank: 2 },
    ],
  },
  {
    id: "EX006",
    name: "Monthly Test – March",
    type: "class_test",
    date: "2026-03-12",
    class: "Class 3",
    subjects: ["Quran"],
    totalMarks: 50,
    status: "draft",
    results: [],
  },
  // ─── Class 2 Exams ───────────────────────────────────────────────────────
  {
    id: "EX007",
    name: "First Semester Exam",
    type: "semester",
    date: "2026-01-24",
    class: "Class 2",
    subjects: ["Quran", "Arabic", "Islamic Studies"],
    totalMarks: 100,
    status: "published",
    results: [
      { studentId: "S008", marks: { Quran: 88, Arabic: 85, "Islamic Studies": 90 }, total: 263, grade: "A+", rank: 1 },
    ],
  },
  {
    id: "EX008",
    name: "Monthly Test – March",
    type: "class_test",
    date: "2026-03-14",
    class: "Class 2",
    subjects: ["Quran"],
    totalMarks: 50,
    status: "draft",
    results: [],
  },
];

// Mock Ibadah Records
export const ibadahRecords = [
  {
    studentId: "S001",
    date: "2026-03-14",
    fajr: "jama",
    zuhr: "jama",
    asr: "individual",
    maghrib: "jama",
    isha: "jama",
    memorization: 95,
    behavior: 5,
    swalaathCount: 5,
    remarks: "Excellent student, very focused",
  },
  {
    studentId: "S002",
    date: "2026-03-14",
    fajr: "individual",
    zuhr: "jama",
    asr: "jama",
    maghrib: "individual",
    isha: "jama",
    memorization: 80,
    behavior: 4,
    swalaathCount: 5,
    remarks: "",
  },
  {
    studentId: "S003",
    date: "2026-03-14",
    fajr: "missed",
    zuhr: "individual",
    asr: "individual",
    maghrib: "jama",
    isha: "individual",
    memorization: 60,
    behavior: 3,
    swalaathCount: 4,
    remarks: "Needs improvement in fajr",
  },
  {
    studentId: "S004",
    date: "2026-03-14",
    fajr: "jama",
    zuhr: "jama",
    asr: "jama",
    maghrib: "jama",
    isha: "jama",
    memorization: 90,
    behavior: 5,
    swalaathCount: 5,
    remarks: "Best student this week",
  },
  {
    studentId: "S005",
    date: "2026-03-14",
    fajr: "jama",
    zuhr: "individual",
    asr: "missed",
    maghrib: "jama",
    isha: "jama",
    memorization: 75,
    behavior: 4,
    swalaathCount: 4,
    remarks: "",
  },
];

// ── Student Ibadah Submissions (submitted by parent on behalf of student) ──
export const studentIbadahSubmissions = [
  // S001 – Ahmed Bin Abdullah – 3 days
  {
    id: "IBS001-1", studentId: "S001", date: "2026-03-17",
    fajr: "jama", zuhr: "jama", asr: "individual", maghrib: "jama", isha: "jama",
    tahajjud: "no", ishraq: "yes", duha: "yes", awwabin: "yes",
    tilawah: "yes", hifz: "yes", tajweed: "partial", revision: "yes",
    tilawahPages: 3, hifzLines: 5,
    subhanallah: 3, alhamdulillah: 3, allahuakbar: 3, istighfar: 2, durood: 2,
    punctual: "yes", respectful: "yes", helpful: "yes", honest: "yes",
    remarks: "Alhamdulillah, completed all prayers on time today.",
    submittedAt: "2026-03-17T20:30:00",
  },
  {
    id: "IBS001-2", studentId: "S001", date: "2026-03-16",
    fajr: "jama", zuhr: "individual", asr: "jama", maghrib: "jama", isha: "jama",
    tahajjud: "no", ishraq: "yes", duha: "partial", awwabin: "yes",
    tilawah: "yes", hifz: "partial", tajweed: "yes", revision: "yes",
    tilawahPages: 2, hifzLines: 3,
    subhanallah: 3, alhamdulillah: 2, allahuakbar: 3, istighfar: 2, durood: 1,
    punctual: "yes", respectful: "yes", helpful: "partial", honest: "yes",
    remarks: "Missed Duha due to school timing.",
    submittedAt: "2026-03-16T21:00:00",
  },
  {
    id: "IBS001-3", studentId: "S001", date: "2026-03-15",
    fajr: "individual", zuhr: "jama", asr: "jama", maghrib: "jama", isha: "individual",
    tahajjud: "no", ishraq: "no", duha: "yes", awwabin: "yes",
    tilawah: "yes", hifz: "yes", tajweed: "yes", revision: "partial",
    tilawahPages: 2, hifzLines: 4,
    subhanallah: 2, alhamdulillah: 2, allahuakbar: 2, istighfar: 1, durood: 2,
    punctual: "partial", respectful: "yes", helpful: "yes", honest: "yes",
    remarks: "",
    submittedAt: "2026-03-15T20:45:00",
  },
  {
    id: "IBS001-4", studentId: "S001", date: "2026-03-14",
    fajr: "jama", zuhr: "jama", asr: "missed", maghrib: "jama", isha: "jama",
    tahajjud: "no", ishraq: "yes", duha: "yes", awwabin: "no",
    tilawah: "partial", hifz: "yes", tajweed: "yes", revision: "yes",
    tilawahPages: 1, hifzLines: 5,
    subhanallah: 3, alhamdulillah: 3, allahuakbar: 3, istighfar: 3, durood: 3,
    punctual: "yes", respectful: "yes", helpful: "yes", honest: "yes",
    remarks: "Missed Asr, was travelling.",
    submittedAt: "2026-03-14T21:15:00",
  },
  {
    id: "IBS001-5", studentId: "S001", date: "2026-03-13",
    fajr: "jama", zuhr: "jama", asr: "jama", maghrib: "jama", isha: "jama",
    tahajjud: "yes", ishraq: "yes", duha: "yes", awwabin: "yes",
    tilawah: "yes", hifz: "yes", tajweed: "yes", revision: "yes",
    tilawahPages: 4, hifzLines: 6,
    subhanallah: 3, alhamdulillah: 3, allahuakbar: 3, istighfar: 3, durood: 3,
    punctual: "yes", respectful: "yes", helpful: "yes", honest: "yes",
    remarks: "Excellent day! All ibadah complete. 🌟",
    submittedAt: "2026-03-13T20:00:00",
  },
  // S006 – Umar Farooq – 3 days
  {
    id: "IBS006-1", studentId: "S006", date: "2026-03-17",
    fajr: "individual", zuhr: "jama", asr: "jama", maghrib: "jama", isha: "jama",
    tahajjud: "no", ishraq: "partial", duha: "yes", awwabin: "no",
    tilawah: "yes", hifz: "partial", tajweed: "yes", revision: "yes",
    tilawahPages: 2, hifzLines: 2,
    subhanallah: 2, alhamdulillah: 2, allahuakbar: 2, istighfar: 1, durood: 1,
    punctual: "partial", respectful: "yes", helpful: "yes", honest: "yes",
    remarks: "Fajr prayed alone at home.",
    submittedAt: "2026-03-17T21:30:00",
  },
  {
    id: "IBS006-2", studentId: "S006", date: "2026-03-16",
    fajr: "jama", zuhr: "jama", asr: "individual", maghrib: "jama", isha: "jama",
    tahajjud: "no", ishraq: "yes", duha: "no", awwabin: "yes",
    tilawah: "yes", hifz: "yes", tajweed: "partial", revision: "partial",
    tilawahPages: 1, hifzLines: 3,
    subhanallah: 3, alhamdulillah: 2, allahuakbar: 3, istighfar: 2, durood: 2,
    punctual: "yes", respectful: "partial", helpful: "yes", honest: "yes",
    remarks: "",
    submittedAt: "2026-03-16T20:50:00",
  },
  {
    id: "IBS006-3", studentId: "S006", date: "2026-03-15",
    fajr: "missed", zuhr: "jama", asr: "jama", maghrib: "individual", isha: "jama",
    tahajjud: "no", ishraq: "no", duha: "partial", awwabin: "no",
    tilawah: "partial", hifz: "yes", tajweed: "yes", revision: "yes",
    tilawahPages: 1, hifzLines: 2,
    subhanallah: 1, alhamdulillah: 1, allahuakbar: 1, istighfar: 1, durood: 1,
    punctual: "partial", respectful: "yes", helpful: "partial", honest: "yes",
    remarks: "Not feeling well, missed Fajr.",
    submittedAt: "2026-03-15T22:00:00",
  },
];

// Mock Fees Records
export const feesRecords = [
  // ── March 2026 ──
  { id:"F001", studentId:"S001", month:"March 2026",    amount:500, status:"paid",    paidDate:"2026-03-05", receiptNumber:"RCP-MAR-001", paymentProof:"proof_s001_mar.jpg" },
  { id:"F002", studentId:"S002", month:"March 2026",    amount:500, status:"pending", paidDate:null,         receiptNumber:null,           paymentProof:"proof_s002_mar.jpg" },
  { id:"F003", studentId:"S003", month:"March 2026",    amount:500, status:"unpaid",  paidDate:null,         receiptNumber:null,           paymentProof:null },
  { id:"F004", studentId:"S004", month:"March 2026",    amount:500, status:"paid",    paidDate:"2026-03-03", receiptNumber:"RCP-MAR-002", paymentProof:"proof_s004_mar.jpg" },
  { id:"F005", studentId:"S005", month:"March 2026",    amount:500, status:"paid",    paidDate:"2026-03-07", receiptNumber:"RCP-MAR-003", paymentProof:"proof_s005_mar.jpg" },
  { id:"F006", studentId:"S006", month:"March 2026",    amount:400, status:"paid",    paidDate:"2026-03-04", receiptNumber:"RCP-MAR-004", paymentProof:"proof_s006_mar.jpg" },
  { id:"F007", studentId:"S007", month:"March 2026",    amount:400, status:"unpaid",  paidDate:null,         receiptNumber:null,           paymentProof:null },
  { id:"F008", studentId:"S008", month:"March 2026",    amount:300, status:"pending", paidDate:null,         receiptNumber:null,           paymentProof:"proof_s008_mar.jpg" },
  // ── February 2026 ──
  { id:"F009", studentId:"S001", month:"February 2026", amount:500, status:"paid",    paidDate:"2026-02-04", receiptNumber:"RCP-FEB-001", paymentProof:"proof_s001_feb.jpg" },
  { id:"F010", studentId:"S002", month:"February 2026", amount:500, status:"paid",    paidDate:"2026-02-06", receiptNumber:"RCP-FEB-002", paymentProof:"proof_s002_feb.jpg" },
  { id:"F011", studentId:"S003", month:"February 2026", amount:500, status:"paid",    paidDate:"2026-02-10", receiptNumber:"RCP-FEB-003", paymentProof:"proof_s003_feb.jpg" },
  { id:"F012", studentId:"S004", month:"February 2026", amount:500, status:"paid",    paidDate:"2026-02-03", receiptNumber:"RCP-FEB-004", paymentProof:"proof_s004_feb.jpg" },
  { id:"F013", studentId:"S005", month:"February 2026", amount:500, status:"unpaid",  paidDate:null,         receiptNumber:null,           paymentProof:null },
  { id:"F014", studentId:"S006", month:"February 2026", amount:400, status:"paid",    paidDate:"2026-02-05", receiptNumber:"RCP-FEB-005", paymentProof:"proof_s006_feb.jpg" },
  { id:"F015", studentId:"S007", month:"February 2026", amount:400, status:"paid",    paidDate:"2026-02-08", receiptNumber:"RCP-FEB-006", paymentProof:"proof_s007_feb.jpg" },
  { id:"F016", studentId:"S008", month:"February 2026", amount:300, status:"paid",    paidDate:"2026-02-07", receiptNumber:"RCP-FEB-007", paymentProof:"proof_s008_feb.jpg" },
  // ── January 2026 ──
  { id:"F017", studentId:"S001", month:"January 2026",  amount:500, status:"paid",    paidDate:"2026-01-05", receiptNumber:"RCP-JAN-001", paymentProof:"proof_s001_jan.jpg" },
  { id:"F018", studentId:"S002", month:"January 2026",  amount:500, status:"paid",    paidDate:"2026-01-07", receiptNumber:"RCP-JAN-002", paymentProof:"proof_s002_jan.jpg" },
  { id:"F019", studentId:"S003", month:"January 2026",  amount:500, status:"unpaid",  paidDate:null,         receiptNumber:null,           paymentProof:null },
  { id:"F020", studentId:"S004", month:"January 2026",  amount:500, status:"paid",    paidDate:"2026-01-04", receiptNumber:"RCP-JAN-003", paymentProof:"proof_s004_jan.jpg" },
  { id:"F021", studentId:"S005", month:"January 2026",  amount:500, status:"paid",    paidDate:"2026-01-09", receiptNumber:"RCP-JAN-004", paymentProof:"proof_s005_jan.jpg" },
  { id:"F022", studentId:"S006", month:"January 2026",  amount:400, status:"paid",    paidDate:"2026-01-06", receiptNumber:"RCP-JAN-005", paymentProof:"proof_s006_jan.jpg" },
  { id:"F023", studentId:"S007", month:"January 2026",  amount:400, status:"pending", paidDate:null,         receiptNumber:null,           paymentProof:"proof_s007_jan.jpg" },
  { id:"F024", studentId:"S008", month:"January 2026",  amount:300, status:"paid",    paidDate:"2026-01-08", receiptNumber:"RCP-JAN-006", paymentProof:"proof_s008_jan.jpg" },
];

// Mock Notifications
export const notifications = [
  {
    id: "N001",
    type: "attendance",
    title: "Attendance Marked",
    message: "Ahmed was marked present today (14 March 2026)",
    timestamp: "2026-03-14T09:30:00",
    read: false,
    parentId: "P001",
  },
  {
    id: "N002",
    type: "homework",
    title: "New Homework Assigned",
    message: "Memorize Surah Al-Asr – Due tomorrow",
    timestamp: "2026-03-14T08:00:00",
    read: false,
    parentId: "P001",
  },
  {
    id: "N003",
    type: "homework",
    title: "Homework Pending",
    message: "Arabic Vocabulary Exercise is still pending for Umar",
    timestamp: "2026-03-14T07:00:00",
    read: true,
    parentId: "P001",
  },
  {
    id: "N004",
    type: "exam",
    title: "Exam Results Published",
    message: "March Monthly Test results are now available",
    timestamp: "2026-03-12T14:00:00",
    read: true,
    parentId: "P001",
  },
  {
    id: "N005",
    type: "fee",
    title: "Fee Reminder",
    message: "March 2026 fee of ₹500 is due. Please pay at the earliest.",
    timestamp: "2026-03-10T10:00:00",
    read: true,
    parentId: "P001",
  },
  {
    id: "N006",
    type: "diary",
    title: "Diary Entry",
    message: "Teacher note: Surah Rahman revision – Please revise again at home",
    timestamp: "2026-03-14T10:30:00",
    read: false,
    parentId: "P001",
  },
];

// Mock Seat Arrangement
export const seatArrangements = [
  {
    id: "SA001",
    examName: "First Semester Exam",
    hall: "Main Hall",
    totalBenches: 20,
    layout: [
      { benchId: 1, row: 1, col: 1, studentId: "S001", studentName: "Ahmed Bin Abdullah", class: "Class 4", gender: "male" },
      { benchId: 2, row: 1, col: 2, studentId: "S006", studentName: "Umar Farooq", class: "Class 3", gender: "male" },
      { benchId: 3, row: 1, col: 3, studentId: "S008", studentName: "Hamza Rashid", class: "Class 2", gender: "male" },
      { benchId: 4, row: 2, col: 1, studentId: "S002", studentName: "Ibrahim Khaleel", class: "Class 4", gender: "male" },
      { benchId: 5, row: 2, col: 2, studentId: "S003", studentName: "Yusuf Salim", class: "Class 4", gender: "male" },
      { benchId: 6, row: 3, col: 1, studentId: "S004", studentName: "Fatima Zahra", class: "Class 4", gender: "female" },
      { benchId: 7, row: 3, col: 2, studentId: "S005", studentName: "Aisha Siddiqui", class: "Class 4", gender: "female" },
      { benchId: 8, row: 3, col: 3, studentId: "S007", studentName: "Maryam Noor", class: "Class 3", gender: "female" },
    ],
  },
];

// Analytics data
export const parentCooperationData = [
  { name: "Active", value: 18, color: "#10b981" },
  { name: "Moderate", value: 8, color: "#f59e0b" },
  { name: "Inactive", value: 4, color: "#ef4444" },
];

export const homeworkCompletionData = [
  { week: "Week 1", completed: 85, pending: 10, missing: 5 },
  { week: "Week 2", completed: 78, pending: 15, missing: 7 },
  { week: "Week 3", completed: 90, pending: 7, missing: 3 },
  { week: "Week 4", completed: 82, pending: 12, missing: 6 },
];

export const monthlyAttendanceData = [
  { month: "Oct", rate: 92 },
  { month: "Nov", rate: 88 },
  { month: "Dec", rate: 85 },
  { month: "Jan", rate: 95 },
  { month: "Feb", rate: 91 },
  { month: "Mar", rate: 94 },
];

export const feeCollectionData = [
  { month: "Oct", collected: 12000, pending: 2500 },
  { month: "Nov", collected: 13500, pending: 1500 },
  { month: "Dec", collected: 11000, pending: 4000 },
  { month: "Jan", collected: 14000, pending: 1000 },
  { month: "Feb", collected: 13000, pending: 2000 },
  { month: "Mar", collected: 10500, pending: 4500 },
];

export const performanceRankingData = [
  { studentId: "S001", name: "Ahmed Bin Abdullah", examScore: 92, ibadah: 95, homework: 98, memorization: 95, total: 380, crown: true, gender: "male" },
  { studentId: "S004", name: "Fatima Zahra", examScore: 88, ibadah: 98, homework: 90, memorization: 92, total: 368, crown: true, gender: "female" },
  { studentId: "S005", name: "Aisha Siddiqui", examScore: 80, ibadah: 85, homework: 82, memorization: 78, total: 325, crown: false, gender: "female" },
  { studentId: "S002", name: "Ibrahim Khaleel", examScore: 78, ibadah: 80, homework: 75, memorization: 80, total: 313, crown: false, gender: "male" },
  { studentId: "S003", name: "Yusuf Salim", examScore: 65, ibadah: 65, homework: 60, memorization: 62, total: 252, crown: false, gender: "male" },
];

export const madrasaConfig = {
  name: "Darul Huda Madrasa",
  samasthaRegNumber: "SMT-KL-2019-4521",
  divisionEnabled: true,
  teachingModel: "subject_based",
  feeEnabled: true,
  feeType: "monthly",
  monthlyFeeAmount: 500,
  classes: ["Class 1", "Class 2", "Class 3", "Class 4", "Class 5", "Class 6"],
  divisions: ["A", "B"],
  address: "Masjid Complex, Calicut, Kerala – 673001",
  phone: "0495-2345678",
  email: "info@darulhuda.edu",
};

export const adminStats = {
  totalStudents: 142,
  totalTeachers: 8,
  totalParents: 130,
  presentToday: 128,
  absentToday: 14,
  feesCollectedThisMonth: 45500,
  feesPending: 26000,
  homeworkCompletionRate: 84,
};

// ── Other Payments (Exam Fees, Book Orders, Fund Campaigns) ─────────────────
export type OtherPaymentCategory =
  | "exam-fees"
  | "book-fees"
  | "samstha-fund"
  | "keithang-charity"
  | "muallim-charity"
  | "other-campaign";

export const otherPaymentCategories = [
  { id: "exam-fees",        label: "Exam Fees",          icon: "GraduationCap", color: "blue"   },
  { id: "book-fees",        label: "Book Order Fees",    icon: "BookOpen",      color: "purple" },
  { id: "samstha-fund",     label: "Samstha Fund",       icon: "Building2",     color: "teal"   },
  { id: "keithang-charity", label: "Keithang Charity",   icon: "Heart",         color: "rose"   },
  { id: "muallim-charity",  label: "Muallim Charity",    icon: "HandHeart",     color: "orange" },
  { id: "other-campaign",   label: "Other Campaigns",    icon: "Megaphone",     color: "amber"  },
];

export const otherPaymentRecords = [
  // Exam Fees
  { id:"OP001", studentId:"S001", category:"exam-fees",        amount:250, status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-10", note:"Term 2 Exam Fee" },
  { id:"OP002", studentId:"S002", category:"exam-fees",        amount:250, status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-12", note:"Term 2 Exam Fee" },
  { id:"OP003", studentId:"S003", category:"exam-fees",        amount:250, status:"pending", dueDate:"2026-03-31", paidDate:null,          note:"Term 2 Exam Fee" },
  { id:"OP004", studentId:"S004", category:"exam-fees",        amount:250, status:"pending", dueDate:"2026-03-31", paidDate:null,          note:"Term 2 Exam Fee" },
  { id:"OP005", studentId:"S005", category:"exam-fees",        amount:250, status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-15", note:"Term 2 Exam Fee" },
  { id:"OP006", studentId:"S006", category:"exam-fees",        amount:200, status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-11", note:"Term 2 Exam Fee" },
  { id:"OP007", studentId:"S007", category:"exam-fees",        amount:200, status:"pending", dueDate:"2026-03-31", paidDate:null,          note:"Term 2 Exam Fee" },
  { id:"OP008", studentId:"S008", category:"exam-fees",        amount:150, status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-09", note:"Term 2 Exam Fee" },
  // Book Order Fees
  { id:"OP009", studentId:"S001", category:"book-fees",        amount:500, status:"paid",    dueDate:"2026-02-28", paidDate:"2026-02-10", note:"Annual book set" },
  { id:"OP010", studentId:"S002", category:"book-fees",        amount:500, status:"paid",    dueDate:"2026-02-28", paidDate:"2026-02-12", note:"Annual book set" },
  { id:"OP011", studentId:"S003", category:"book-fees",        amount:500, status:"pending", dueDate:"2026-02-28", paidDate:null,          note:"Annual book set" },
  { id:"OP012", studentId:"S004", category:"book-fees",        amount:500, status:"paid",    dueDate:"2026-02-28", paidDate:"2026-02-14", note:"Annual book set" },
  { id:"OP013", studentId:"S005", category:"book-fees",        amount:500, status:"pending", dueDate:"2026-02-28", paidDate:null,          note:"Annual book set" },
  { id:"OP014", studentId:"S006", category:"book-fees",        amount:400, status:"paid",    dueDate:"2026-02-28", paidDate:"2026-02-11", note:"Annual book set" },
  { id:"OP015", studentId:"S007", category:"book-fees",        amount:400, status:"paid",    dueDate:"2026-02-28", paidDate:"2026-02-13", note:"Annual book set" },
  { id:"OP016", studentId:"S008", category:"book-fees",        amount:350, status:"pending", dueDate:"2026-02-28", paidDate:null,          note:"Annual book set" },
  // Samstha Fund
  { id:"OP017", studentId:"S001", category:"samstha-fund",     amount:100, status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-05", note:"Annual Samstha contribution" },
  { id:"OP018", studentId:"S002", category:"samstha-fund",     amount:100, status:"pending", dueDate:"2026-03-31", paidDate:null,          note:"Annual Samstha contribution" },
  { id:"OP019", studentId:"S003", category:"samstha-fund",     amount:100, status:"pending", dueDate:"2026-03-31", paidDate:null,          note:"Annual Samstha contribution" },
  { id:"OP020", studentId:"S004", category:"samstha-fund",     amount:100, status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-06", note:"Annual Samstha contribution" },
  { id:"OP021", studentId:"S005", category:"samstha-fund",     amount:100, status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-07", note:"Annual Samstha contribution" },
  // Keithang Charity
  { id:"OP022", studentId:"S001", category:"keithang-charity", amount:50,  status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-08", note:"Keithang charity drive 2026" },
  { id:"OP023", studentId:"S002", category:"keithang-charity", amount:50,  status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-09", note:"Keithang charity drive 2026" },
  { id:"OP024", studentId:"S003", category:"keithang-charity", amount:50,  status:"pending", dueDate:"2026-03-31", paidDate:null,          note:"Keithang charity drive 2026" },
  { id:"OP025", studentId:"S004", category:"keithang-charity", amount:50,  status:"pending", dueDate:"2026-03-31", paidDate:null,          note:"Keithang charity drive 2026" },
  { id:"OP026", studentId:"S005", category:"keithang-charity", amount:50,  status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-10", note:"Keithang charity drive 2026" },
  { id:"OP027", studentId:"S006", category:"keithang-charity", amount:50,  status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-10", note:"Keithang charity drive 2026" },
  // Muallim Charity
  { id:"OP028", studentId:"S001", category:"muallim-charity",  amount:75,  status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-11", note:"Muallim welfare fund" },
  { id:"OP029", studentId:"S002", category:"muallim-charity",  amount:75,  status:"pending", dueDate:"2026-03-31", paidDate:null,          note:"Muallim welfare fund" },
  { id:"OP030", studentId:"S003", category:"muallim-charity",  amount:75,  status:"pending", dueDate:"2026-03-31", paidDate:null,          note:"Muallim welfare fund" },
  { id:"OP031", studentId:"S004", category:"muallim-charity",  amount:75,  status:"paid",    dueDate:"2026-03-31", paidDate:"2026-03-12", note:"Muallim welfare fund" },
  // Other Campaign
  { id:"OP032", studentId:"S001", category:"other-campaign",   amount:200, status:"paid",    dueDate:"2026-04-15", paidDate:"2026-03-20", note:"Madrasa Building Fund" },
  { id:"OP033", studentId:"S002", category:"other-campaign",   amount:200, status:"pending", dueDate:"2026-04-15", paidDate:null,          note:"Madrasa Building Fund" },
  { id:"OP034", studentId:"S005", category:"other-campaign",   amount:200, status:"pending", dueDate:"2026-04-15", paidDate:null,          note:"Madrasa Building Fund" },
];

// ── Student ID Cards ──────────────────────────────────────────────────────────
export const idCardSettings = {
  madrasaName: "Darul Huda Madrasa",
  madrasaAddress: "Mosque Road, Calicut, Kerala – 673001",
  madrasaPhone: "0495-2765432",
  academicYear: "2025–2026",
  primaryColor: "#059669",
  logoText: "DH",
};

// ── SKSBV Student Union ───────────────────────────────────────────────────────
export const sksbvData = {
  name: "SKSBV",
  fullName: "Sunni Kuttikalude Sanghatana Balan Vedi",
  established: "2019",
  motto: "Knowledge, Faith & Service",
  executive: [
    { id:"EX01", studentId:"S001", name:"Ahmed Bin Abdullah", role:"President",          class:"Class 4", photo:null },
    { id:"EX02", studentId:"S004", name:"Fatima Zahra",       role:"Vice President",     class:"Class 4", photo:null },
    { id:"EX03", studentId:"S002", name:"Ibrahim Khaleel",    role:"General Secretary",  class:"Class 4", photo:null },
    { id:"EX04", studentId:"S005", name:"Aisha Siddiqui",     role:"Treasurer",          class:"Class 4", photo:null },
    { id:"EX05", studentId:"S006", name:"Umar Farooq",        role:"Class Rep – Class 3",class:"Class 3", photo:null },
    { id:"EX06", studentId:"S007", name:"Maryam Noor",        role:"Class Rep – Class 3",class:"Class 3", photo:null },
    { id:"EX07", studentId:"S008", name:"Hamza Rashid",       role:"Class Rep – Class 2",class:"Class 2", photo:null },
  ],
  programs: [
    {
      id:"SK001", title:"Quran Recitation Competition", category:"Academic",
      date:"2026-04-10", status:"upcoming", venue:"Main Hall",
      description:"Inter-class Quran recitation with tajweed evaluation.",
      participants:40, coordinator:"Usthad Abdul Kareem", budget:2000,
    },
    {
      id:"SK002", title:"Islamic Quiz Bowl", category:"Academic",
      date:"2026-03-20", status:"completed", venue:"Classroom Block",
      description:"20-team quiz on Fiqh, Hadith, and Seerah. Winners get certificates.",
      participants:80, coordinator:"Usthad Rasheed", budget:1500, winner:"Class 4A",
    },
    {
      id:"SK003", title:"Charity Collection – Ramadan", category:"Charity",
      date:"2026-03-15", status:"completed", venue:"School Premises",
      description:"Students collected donations for needy families during Ramadan.",
      participants:142, coordinator:"Usthada Zubeda", budget:0, collected:8500,
    },
    {
      id:"SK004", title:"Nasheeds & Madh Night", category:"Cultural",
      date:"2026-05-02", status:"upcoming", venue:"School Auditorium",
      description:"Evening of Islamic nasheeds, poetry, and qasidas by students.",
      participants:60, coordinator:"Usthad Abdul Kareem", budget:3000,
    },
    {
      id:"SK005", title:"Sports & Games Day", category:"Sports",
      date:"2026-05-15", status:"upcoming", venue:"School Ground",
      description:"Cricket, football, and track events for all classes.",
      participants:142, coordinator:"Usthad Rasheed", budget:2500,
    },
    {
      id:"SK006", title:"Annual Picnic & Outing", category:"Outing",
      date:"2026-02-28", status:"completed", venue:"Calicut Beach Park",
      description:"Annual recreational outing for all students and staff.",
      participants:120, coordinator:"Usthada Zubeda", budget:5000,
    },
    {
      id:"SK007", title:"Parents Interaction Day", category:"Community",
      date:"2026-04-25", status:"upcoming", venue:"Main Hall",
      description:"SKSBV-organised event for parents to interact with union leaders.",
      participants:50, coordinator:"Usthad Abdul Kareem", budget:1000,
    },
    {
      id:"SK008", title:"Blood Donation Drive", category:"Charity",
      date:"2026-01-10", status:"completed", venue:"School Premises",
      description:"Community blood donation drive organised by SKSBV in collaboration with local hospital.",
      participants:25, coordinator:"Usthad Rasheed", budget:500, collected:0,
    },
  ],
  stats: {
    totalMembers: 142, executiveCount: 7,
    programsThisYear: 8, completedPrograms: 4,
    totalBudget: 15500, fundsRaised: 8500,
  },
};
