// Mock Students
export const students = [
  {
    id: "S001",
    admissionNumber: "MDA-2024-001",
    name: "Ahmed Bin Abdullah",
    gender: "male",
    dateOfBirth: "2014-03-12",
    address: "12, Mosque Road, Calicut",
    photo: null,
    class: "Class 4",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P001",
    fatherName: "Abdullah Rahman",
    motherName: "Fathima Bivi",
    phone: "9876543210",
  },
  {
    id: "S002",
    admissionNumber: "MDA-2024-002",
    name: "Ibrahim Khaleel",
    gender: "male",
    dateOfBirth: "2013-08-22",
    address: "45, Palm Street, Calicut",
    photo: null,
    class: "Class 4",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P002",
    fatherName: "Khaleel Ahmed",
    motherName: "Mariam Beevi",
    phone: "9876543211",
  },
  {
    id: "S003",
    admissionNumber: "MDA-2024-003",
    name: "Yusuf Salim",
    gender: "male",
    dateOfBirth: "2014-01-05",
    address: "78, Green Lane, Calicut",
    photo: null,
    class: "Class 4",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P003",
    fatherName: "Salim Mohammed",
    motherName: "Zainab Beevi",
    phone: "9876543212",
  },
  {
    id: "S004",
    admissionNumber: "MDA-2024-004",
    name: "Fatima Zahra",
    gender: "female",
    dateOfBirth: "2014-05-15",
    address: "33, Rose Garden, Calicut",
    photo: null,
    class: "Class 4",
    division: "B",
    joiningDate: "2024-06-01",
    parentId: "P004",
    fatherName: "Zakariya Hassan",
    motherName: "Khadija Beevi",
    phone: "9876543213",
  },
  {
    id: "S005",
    admissionNumber: "MDA-2024-005",
    name: "Aisha Siddiqui",
    gender: "female",
    dateOfBirth: "2013-11-30",
    address: "22, Crescent Avenue, Calicut",
    photo: null,
    class: "Class 4",
    division: "B",
    joiningDate: "2024-06-01",
    parentId: "P005",
    fatherName: "Siddique Ali",
    motherName: "Ruqaiya Beevi",
    phone: "9876543214",
  },
  {
    id: "S006",
    admissionNumber: "MDA-2024-006",
    name: "Umar Farooq",
    gender: "male",
    dateOfBirth: "2015-02-18",
    address: "56, Hilal Street, Calicut",
    photo: null,
    class: "Class 3",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P001",
    fatherName: "Abdullah Rahman",
    motherName: "Fathima Bivi",
    phone: "9876543210",
  },
  {
    id: "S007",
    admissionNumber: "MDA-2024-007",
    name: "Maryam Noor",
    gender: "female",
    dateOfBirth: "2015-07-09",
    address: "90, Jasmine Road, Calicut",
    photo: null,
    class: "Class 3",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P006",
    fatherName: "Noor Mohammed",
    motherName: "Hafsa Beevi",
    phone: "9876543215",
  },
  {
    id: "S008",
    admissionNumber: "MDA-2024-008",
    name: "Hamza Rashid",
    gender: "male",
    dateOfBirth: "2016-04-25",
    address: "14, Olive Street, Calicut",
    photo: null,
    class: "Class 2",
    division: "A",
    joiningDate: "2024-06-01",
    parentId: "P007",
    fatherName: "Rashid Ahmed",
    motherName: "Sumaiya Beevi",
    phone: "9876543216",
  },
];

// Mock Teachers
export const teachers = [
  {
    id: "T001",
    name: "Usthad Abdul Kareem",
    phone: "9988776655",
    email: "kareem@madrasa.com",
    subject: "Quran & Islamic Studies",
    classes: ["Class 4", "Class 3"],
    joiningDate: "2020-06-01",
    qualification: "B.A Islamic Studies",
  },
  {
    id: "T002",
    name: "Usthada Zubeda",
    phone: "9988776644",
    email: "zubeda@madrasa.com",
    subject: "Arabic",
    classes: ["Class 4", "Class 2"],
    joiningDate: "2021-06-01",
    qualification: "M.A Arabic",
  },
  {
    id: "T003",
    name: "Usthad Rasheed",
    phone: "9988776633",
    email: "rasheed@madrasa.com",
    subject: "Fiqh & Hadith",
    classes: ["Class 3"],
    joiningDate: "2019-06-01",
    qualification: "Dars Graduation",
  },
];

// Mock Parents
export const parents = [
  {
    id: "P001",
    fatherName: "Abdullah Rahman",
    motherName: "Fathima Bivi",
    phone: "9876543210",
    email: "abdullah@email.com",
    password: "parent123",
    children: ["S001", "S006"],
  },
  {
    id: "P002",
    fatherName: "Khaleel Ahmed",
    motherName: "Mariam Beevi",
    phone: "9876543211",
    email: "khaleel@email.com",
    password: "parent123",
    children: ["S002"],
  },
  {
    id: "P003",
    fatherName: "Salim Mohammed",
    motherName: "Zainab Beevi",
    phone: "9876543212",
    email: "salim@email.com",
    password: "parent123",
    children: ["S003"],
  },
  {
    id: "P004",
    fatherName: "Zakariya Hassan",
    motherName: "Khadija Beevi",
    phone: "9876543213",
    email: "zakariya@email.com",
    password: "parent123",
    children: ["S004"],
  },
  {
    id: "P005",
    fatherName: "Siddique Ali",
    motherName: "Ruqaiya Beevi",
    phone: "9876543214",
    email: "siddique@email.com",
    password: "parent123",
    children: ["S005"],
  },
];

// Mock Attendance Records
export const attendanceRecords = [
  {
    date: "2026-03-14",
    classId: "Class 4",
    records: [
      { studentId: "S001", status: "present" },
      { studentId: "S002", status: "present" },
      { studentId: "S003", status: "absent" },
      { studentId: "S004", status: "present" },
      { studentId: "S005", status: "present" },
    ],
  },
  {
    date: "2026-03-13",
    classId: "Class 4",
    records: [
      { studentId: "S001", status: "present" },
      { studentId: "S002", status: "absent" },
      { studentId: "S003", status: "present" },
      { studentId: "S004", status: "present" },
      { studentId: "S005", status: "absent" },
    ],
  },
  {
    date: "2026-03-12",
    classId: "Class 4",
    records: [
      { studentId: "S001", status: "present" },
      { studentId: "S002", status: "present" },
      { studentId: "S003", status: "present" },
      { studentId: "S004", status: "absent" },
      { studentId: "S005", status: "present" },
    ],
  },
];

export const attendanceSummary = [
  { month: "Oct", present: 22, absent: 2 },
  { month: "Nov", present: 20, absent: 4 },
  { month: "Dec", present: 18, absent: 6 },
  { month: "Jan", present: 23, absent: 1 },
  { month: "Feb", present: 21, absent: 3 },
  { month: "Mar", present: 10, absent: 1 },
];

// Mock Homework
export const homeworkList = [
  {
    id: "HW001",
    type: "daily",
    title: "Memorize Surah Al-Asr",
    description: "Memorize Surah Al-Asr with proper tajweed",
    assignedDate: "2026-03-14",
    dueDate: "2026-03-15",
    class: "Class 4",
    teacherId: "T001",
    subject: "Quran",
    studentStatuses: [
      { studentId: "S001", status: "green", parentConfirmed: true, teacherVerified: true },
      { studentId: "S002", status: "yellow", parentConfirmed: true, teacherVerified: false },
      { studentId: "S003", status: "red", parentConfirmed: false, teacherVerified: false },
      { studentId: "S004", status: "green", parentConfirmed: true, teacherVerified: true },
      { studentId: "S005", status: "yellow", parentConfirmed: true, teacherVerified: false },
    ],
  },
  {
    id: "HW002",
    type: "long",
    title: "Memorize Surah Al-Kahf (1-20)",
    description: "Memorize first 20 ayahs of Surah Al-Kahf",
    assignedDate: "2026-03-10",
    dueDate: "2026-03-20",
    class: "Class 4",
    teacherId: "T001",
    subject: "Quran",
    studentStatuses: [
      { studentId: "S001", status: "green", parentConfirmed: true, teacherVerified: true, progress: 100 },
      { studentId: "S002", status: "yellow", parentConfirmed: true, teacherVerified: false, progress: 60 },
      { studentId: "S003", status: "red", parentConfirmed: false, teacherVerified: false, progress: 0 },
      { studentId: "S004", status: "yellow", parentConfirmed: true, teacherVerified: false, progress: 80 },
      { studentId: "S005", status: "red", parentConfirmed: false, teacherVerified: false, progress: 20 },
    ],
  },
  {
    id: "HW003",
    type: "daily",
    title: "Arabic Vocabulary Exercise",
    description: "Complete exercises on page 45",
    assignedDate: "2026-03-14",
    dueDate: "2026-03-15",
    class: "Class 4",
    teacherId: "T002",
    subject: "Arabic",
    studentStatuses: [
      { studentId: "S001", status: "yellow", parentConfirmed: true, teacherVerified: false },
      { studentId: "S002", status: "green", parentConfirmed: true, teacherVerified: true },
      { studentId: "S003", status: "yellow", parentConfirmed: true, teacherVerified: false },
      { studentId: "S004", status: "red", parentConfirmed: false, teacherVerified: false },
      { studentId: "S005", status: "green", parentConfirmed: true, teacherVerified: true },
    ],
  },
];

// Mock Diary Entries
export const diaryEntries = [
  {
    id: "D001",
    date: "2026-03-14",
    class: "Class 4",
    teacherId: "T001",
    type: "class",
    title: "Surah Rahman Revision",
    content: "Today students revised Surah Rahman verses 1-30. Overall recitation was good. Please revise again at home with proper tajweed focus on makhraj.",
    targetStudentId: null,
  },
  {
    id: "D002",
    date: "2026-03-14",
    class: "Class 4",
    teacherId: "T001",
    type: "student",
    title: "Special Note – Ahmed",
    content: "Ahmed showed excellent improvement in tajweed today. His makhraj for 'ain and ghayn are now correct. Encourage him to continue.",
    targetStudentId: "S001",
  },
  {
    id: "D003",
    date: "2026-03-13",
    class: "Class 4",
    teacherId: "T001",
    type: "class",
    title: "New Lesson Started",
    content: "Started new chapter on Surah Al-Kahf. Students were given first 5 ayahs for home memorization. Please ensure daily revision.",
    targetStudentId: null,
  },
];

// Mock Exam Records
export const exams = [
  {
    id: "EX001",
    name: "First Semester Exam",
    type: "semester",
    date: "2026-01-20",
    class: "Class 4",
    subjects: ["Quran", "Arabic", "Fiqh", "Islamic Studies"],
    totalMarks: 100,
    results: [
      {
        studentId: "S001",
        marks: { Quran: 92, Arabic: 88, Fiqh: 85, "Islamic Studies": 90 },
        total: 355,
        grade: "A+",
        rank: 1,
      },
      {
        studentId: "S002",
        marks: { Quran: 78, Arabic: 82, Fiqh: 75, "Islamic Studies": 80 },
        total: 315,
        grade: "B+",
        rank: 3,
      },
      {
        studentId: "S003",
        marks: { Quran: 65, Arabic: 70, Fiqh: 60, "Islamic Studies": 72 },
        total: 267,
        grade: "C",
        rank: 5,
      },
      {
        studentId: "S004",
        marks: { Quran: 88, Arabic: 90, Fiqh: 82, "Islamic Studies": 86 },
        total: 346,
        grade: "A",
        rank: 2,
      },
      {
        studentId: "S005",
        marks: { Quran: 80, Arabic: 76, Fiqh: 78, "Islamic Studies": 82 },
        total: 316,
        grade: "B+",
        rank: 3,
      },
    ],
  },
  {
    id: "EX002",
    name: "Monthly Test – March",
    type: "class_test",
    date: "2026-03-10",
    class: "Class 4",
    subjects: ["Quran"],
    totalMarks: 50,
    results: [
      { studentId: "S001", marks: { Quran: 47 }, total: 47, grade: "A+", rank: 1 },
      { studentId: "S002", marks: { Quran: 38 }, total: 38, grade: "B", rank: 3 },
      { studentId: "S003", marks: { Quran: 30 }, total: 30, grade: "C", rank: 5 },
      { studentId: "S004", marks: { Quran: 44 }, total: 44, grade: "A", rank: 2 },
      { studentId: "S005", marks: { Quran: 40 }, total: 40, grade: "B+", rank: 3 },
    ],
  },
];

// Mock Ibadah Records
export const ibadahRecords = [
  {
    studentId: "S001",
    date: "2026-03-14",
    fajr: "jama",
    zuhr: "jama",
    asr: "individual",
    maghrib: "jama",
    isha: "jama",
    memorization: 95,
    behavior: 5,
    swalaathCount: 5,
    remarks: "Excellent student, very focused",
  },
  {
    studentId: "S002",
    date: "2026-03-14",
    fajr: "individual",
    zuhr: "jama",
    asr: "jama",
    maghrib: "individual",
    isha: "jama",
    memorization: 80,
    behavior: 4,
    swalaathCount: 5,
    remarks: "",
  },
  {
    studentId: "S003",
    date: "2026-03-14",
    fajr: "missed",
    zuhr: "individual",
    asr: "individual",
    maghrib: "jama",
    isha: "individual",
    memorization: 60,
    behavior: 3,
    swalaathCount: 4,
    remarks: "Needs improvement in fajr",
  },
  {
    studentId: "S004",
    date: "2026-03-14",
    fajr: "jama",
    zuhr: "jama",
    asr: "jama",
    maghrib: "jama",
    isha: "jama",
    memorization: 90,
    behavior: 5,
    swalaathCount: 5,
    remarks: "Best student this week",
  },
  {
    studentId: "S005",
    date: "2026-03-14",
    fajr: "jama",
    zuhr: "individual",
    asr: "missed",
    maghrib: "jama",
    isha: "jama",
    memorization: 75,
    behavior: 4,
    swalaathCount: 4,
    remarks: "",
  },
];

// Mock Fees Records
export const feesRecords = [
  {
    id: "F001",
    studentId: "S001",
    month: "March 2026",
    amount: 500,
    status: "paid",
    paidDate: "2026-03-05",
    receiptNumber: "RCP-2026-001",
    paymentProof: "proof_s001_mar.jpg",
  },
  {
    id: "F002",
    studentId: "S002",
    month: "March 2026",
    amount: 500,
    status: "pending",
    paidDate: null,
    receiptNumber: null,
    paymentProof: "proof_s002_mar.jpg",
  },
  {
    id: "F003",
    studentId: "S003",
    month: "March 2026",
    amount: 500,
    status: "unpaid",
    paidDate: null,
    receiptNumber: null,
    paymentProof: null,
  },
  {
    id: "F004",
    studentId: "S004",
    month: "March 2026",
    amount: 500,
    status: "paid",
    paidDate: "2026-03-03",
    receiptNumber: "RCP-2026-002",
    paymentProof: "proof_s004_mar.jpg",
  },
  {
    id: "F005",
    studentId: "S005",
    month: "March 2026",
    amount: 500,
    status: "paid",
    paidDate: "2026-03-07",
    receiptNumber: "RCP-2026-003",
    paymentProof: "proof_s005_mar.jpg",
  },
  {
    id: "F006",
    studentId: "S001",
    month: "February 2026",
    amount: 500,
    status: "paid",
    paidDate: "2026-02-04",
    receiptNumber: "RCP-2026-FEB-001",
    paymentProof: "proof_s001_feb.jpg",
  },
];

// Mock Notifications
export const notifications = [
  {
    id: "N001",
    type: "attendance",
    title: "Attendance Marked",
    message: "Ahmed was marked present today (14 March 2026)",
    timestamp: "2026-03-14T09:30:00",
    read: false,
    parentId: "P001",
  },
  {
    id: "N002",
    type: "homework",
    title: "New Homework Assigned",
    message: "Memorize Surah Al-Asr – Due tomorrow",
    timestamp: "2026-03-14T08:00:00",
    read: false,
    parentId: "P001",
  },
  {
    id: "N003",
    type: "homework",
    title: "Homework Pending",
    message: "Arabic Vocabulary Exercise is still pending for Umar",
    timestamp: "2026-03-14T07:00:00",
    read: true,
    parentId: "P001",
  },
  {
    id: "N004",
    type: "exam",
    title: "Exam Results Published",
    message: "March Monthly Test results are now available",
    timestamp: "2026-03-12T14:00:00",
    read: true,
    parentId: "P001",
  },
  {
    id: "N005",
    type: "fee",
    title: "Fee Reminder",
    message: "March 2026 fee of ₹500 is due. Please pay at the earliest.",
    timestamp: "2026-03-10T10:00:00",
    read: true,
    parentId: "P001",
  },
  {
    id: "N006",
    type: "diary",
    title: "Diary Entry",
    message: "Teacher note: Surah Rahman revision – Please revise again at home",
    timestamp: "2026-03-14T10:30:00",
    read: false,
    parentId: "P001",
  },
];

// Mock Seat Arrangement
export const seatArrangements = [
  {
    id: "SA001",
    examName: "First Semester Exam",
    hall: "Main Hall",
    totalBenches: 20,
    layout: [
      { benchId: 1, row: 1, col: 1, studentId: "S001", studentName: "Ahmed Bin Abdullah", class: "Class 4", gender: "male" },
      { benchId: 2, row: 1, col: 2, studentId: "S006", studentName: "Umar Farooq", class: "Class 3", gender: "male" },
      { benchId: 3, row: 1, col: 3, studentId: "S008", studentName: "Hamza Rashid", class: "Class 2", gender: "male" },
      { benchId: 4, row: 2, col: 1, studentId: "S002", studentName: "Ibrahim Khaleel", class: "Class 4", gender: "male" },
      { benchId: 5, row: 2, col: 2, studentId: "S003", studentName: "Yusuf Salim", class: "Class 4", gender: "male" },
      { benchId: 6, row: 3, col: 1, studentId: "S004", studentName: "Fatima Zahra", class: "Class 4", gender: "female" },
      { benchId: 7, row: 3, col: 2, studentId: "S005", studentName: "Aisha Siddiqui", class: "Class 4", gender: "female" },
      { benchId: 8, row: 3, col: 3, studentId: "S007", studentName: "Maryam Noor", class: "Class 3", gender: "female" },
    ],
  },
];

// Analytics data
export const parentCooperationData = [
  { name: "Active", value: 18, color: "#10b981" },
  { name: "Moderate", value: 8, color: "#f59e0b" },
  { name: "Inactive", value: 4, color: "#ef4444" },
];

export const homeworkCompletionData = [
  { week: "Week 1", completed: 85, pending: 10, missing: 5 },
  { week: "Week 2", completed: 78, pending: 15, missing: 7 },
  { week: "Week 3", completed: 90, pending: 7, missing: 3 },
  { week: "Week 4", completed: 82, pending: 12, missing: 6 },
];

export const monthlyAttendanceData = [
  { month: "Oct", rate: 92 },
  { month: "Nov", rate: 88 },
  { month: "Dec", rate: 85 },
  { month: "Jan", rate: 95 },
  { month: "Feb", rate: 91 },
  { month: "Mar", rate: 94 },
];

export const feeCollectionData = [
  { month: "Oct", collected: 12000, pending: 2500 },
  { month: "Nov", collected: 13500, pending: 1500 },
  { month: "Dec", collected: 11000, pending: 4000 },
  { month: "Jan", collected: 14000, pending: 1000 },
  { month: "Feb", collected: 13000, pending: 2000 },
  { month: "Mar", collected: 10500, pending: 4500 },
];

export const performanceRankingData = [
  { studentId: "S001", name: "Ahmed Bin Abdullah", examScore: 92, ibadah: 95, homework: 98, memorization: 95, total: 380, crown: true, gender: "male" },
  { studentId: "S004", name: "Fatima Zahra", examScore: 88, ibadah: 98, homework: 90, memorization: 92, total: 368, crown: true, gender: "female" },
  { studentId: "S005", name: "Aisha Siddiqui", examScore: 80, ibadah: 85, homework: 82, memorization: 78, total: 325, crown: false, gender: "female" },
  { studentId: "S002", name: "Ibrahim Khaleel", examScore: 78, ibadah: 80, homework: 75, memorization: 80, total: 313, crown: false, gender: "male" },
  { studentId: "S003", name: "Yusuf Salim", examScore: 65, ibadah: 65, homework: 60, memorization: 62, total: 252, crown: false, gender: "male" },
];

export const madrasaConfig = {
  name: "Darul Huda Madrasa",
  samasthaRegNumber: "SMT-KL-2019-4521",
  divisionEnabled: true,
  teachingModel: "subject_based",
  feeEnabled: true,
  feeType: "monthly",
  monthlyFeeAmount: 500,
  classes: ["Class 1", "Class 2", "Class 3", "Class 4", "Class 5", "Class 6"],
  divisions: ["A", "B"],
  address: "Masjid Complex, Calicut, Kerala – 673001",
  phone: "0495-2345678",
  email: "info@darulhuda.edu",
};

export const adminStats = {
  totalStudents: 142,
  totalTeachers: 8,
  totalParents: 130,
  presentToday: 128,
  absentToday: 14,
  feesCollectedThisMonth: 45500,
  feesPending: 26000,
  homeworkCompletionRate: 84,
};
